# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LutRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'Uuid',
        'frame': 'int',
        'file': 'str',
        'lut_type': 'str'
    }

    attribute_map = {
        'uuid': 'uuid',
        'frame': 'frame',
        'file': 'file',
        'lut_type': 'lut_type'
    }

    def __init__(self, uuid=None, frame=None, file=None, lut_type=None):  # noqa: E501
        """LutRequest - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._frame = None
        self._file = None
        self._lut_type = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if frame is not None:
            self.frame = frame
        if file is not None:
            self.file = file
        if lut_type is not None:
            self.lut_type = lut_type

    @property
    def uuid(self):
        """Gets the uuid of this LutRequest.  # noqa: E501


        :return: The uuid of this LutRequest.  # noqa: E501
        :rtype: Uuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this LutRequest.


        :param uuid: The uuid of this LutRequest.  # noqa: E501
        :type: Uuid
        """

        self._uuid = uuid

    @property
    def frame(self):
        """Gets the frame of this LutRequest.  # noqa: E501

        Frame number to create the image from  # noqa: E501

        :return: The frame of this LutRequest.  # noqa: E501
        :rtype: int
        """
        return self._frame

    @frame.setter
    def frame(self, frame):
        """Sets the frame of this LutRequest.

        Frame number to create the image from  # noqa: E501

        :param frame: The frame of this LutRequest.  # noqa: E501
        :type: int
        """

        self._frame = frame

    @property
    def file(self):
        """Gets the file of this LutRequest.  # noqa: E501

        Full file path name on the local http server. Supported file formats are *.cube, *.3dl, *.lut, *.xml and *.txt.  # noqa: E501

        :return: The file of this LutRequest.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this LutRequest.

        Full file path name on the local http server. Supported file formats are *.cube, *.3dl, *.lut, *.xml and *.txt.  # noqa: E501

        :param file: The file of this LutRequest.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def lut_type(self):
        """Gets the lut_type of this LutRequest.  # noqa: E501

        LUT type to be generated. Supported LUT types are cube, 3dl, lut, xml and txt.  # noqa: E501

        :return: The lut_type of this LutRequest.  # noqa: E501
        :rtype: str
        """
        return self._lut_type

    @lut_type.setter
    def lut_type(self, lut_type):
        """Sets the lut_type of this LutRequest.

        LUT type to be generated. Supported LUT types are cube, 3dl, lut, xml and txt.  # noqa: E501

        :param lut_type: The lut_type of this LutRequest.  # noqa: E501
        :type: str
        """

        self._lut_type = lut_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LutRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LutRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
