# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlaymodeData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'audio': 'str',
        'fps': 'float',
        'construct_uuid': 'Uuid',
        'frame': 'int',
        'timecodec': 'str',
        'slot_index': 'int',
        'shot_uuid': 'Uuid',
        'shot_frame': 'int',
        'shot_timecode': 'str',
        'version': 'int',
        'session': 'str',
        'length': 'int',
        'loop': 'str',
        'mark_in': 'int',
        'mark_out': 'int',
        'mode': 'str',
        'range': 'bool',
        'speed': 'int',
        'timeline': 'str'
    }

    attribute_map = {
        'audio': 'audio',
        'fps': 'fps',
        'construct_uuid': 'construct_uuid',
        'frame': 'frame',
        'timecodec': 'timecodec',
        'slot_index': 'slot_index',
        'shot_uuid': 'shot_uuid',
        'shot_frame': 'shot_frame',
        'shot_timecode': 'shot_timecode',
        'version': 'version',
        'session': 'session',
        'length': 'length',
        'loop': 'loop',
        'mark_in': 'mark_in',
        'mark_out': 'mark_out',
        'mode': 'mode',
        'range': 'range',
        'speed': 'speed',
        'timeline': 'timeline'
    }

    def __init__(self, audio=None, fps=None, construct_uuid=None, frame=None, timecodec=None, slot_index=None, shot_uuid=None, shot_frame=None, shot_timecode=None, version=None, session=None, length=None, loop=None, mark_in=None, mark_out=None, mode=None, range=None, speed=None, timeline=None):  # noqa: E501
        """PlaymodeData - a model defined in Swagger"""  # noqa: E501
        self._audio = None
        self._fps = None
        self._construct_uuid = None
        self._frame = None
        self._timecodec = None
        self._slot_index = None
        self._shot_uuid = None
        self._shot_frame = None
        self._shot_timecode = None
        self._version = None
        self._session = None
        self._length = None
        self._loop = None
        self._mark_in = None
        self._mark_out = None
        self._mode = None
        self._range = None
        self._speed = None
        self._timeline = None
        self.discriminator = None
        if audio is not None:
            self.audio = audio
        if fps is not None:
            self.fps = fps
        if construct_uuid is not None:
            self.construct_uuid = construct_uuid
        if frame is not None:
            self.frame = frame
        if timecodec is not None:
            self.timecodec = timecodec
        if slot_index is not None:
            self.slot_index = slot_index
        if shot_uuid is not None:
            self.shot_uuid = shot_uuid
        if shot_frame is not None:
            self.shot_frame = shot_frame
        if shot_timecode is not None:
            self.shot_timecode = shot_timecode
        if version is not None:
            self.version = version
        if session is not None:
            self.session = session
        if length is not None:
            self.length = length
        if loop is not None:
            self.loop = loop
        if mark_in is not None:
            self.mark_in = mark_in
        if mark_out is not None:
            self.mark_out = mark_out
        if mode is not None:
            self.mode = mode
        if range is not None:
            self.range = range
        if speed is not None:
            self.speed = speed
        if timeline is not None:
            self.timeline = timeline

    @property
    def audio(self):
        """Gets the audio of this PlaymodeData.  # noqa: E501

        Audio settings  # noqa: E501

        :return: The audio of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this PlaymodeData.

        Audio settings  # noqa: E501

        :param audio: The audio of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._audio = audio

    @property
    def fps(self):
        """Gets the fps of this PlaymodeData.  # noqa: E501

        Playback framerate  # noqa: E501

        :return: The fps of this PlaymodeData.  # noqa: E501
        :rtype: float
        """
        return self._fps

    @fps.setter
    def fps(self, fps):
        """Sets the fps of this PlaymodeData.

        Playback framerate  # noqa: E501

        :param fps: The fps of this PlaymodeData.  # noqa: E501
        :type: float
        """

        self._fps = fps

    @property
    def construct_uuid(self):
        """Gets the construct_uuid of this PlaymodeData.  # noqa: E501


        :return: The construct_uuid of this PlaymodeData.  # noqa: E501
        :rtype: Uuid
        """
        return self._construct_uuid

    @construct_uuid.setter
    def construct_uuid(self, construct_uuid):
        """Sets the construct_uuid of this PlaymodeData.


        :param construct_uuid: The construct_uuid of this PlaymodeData.  # noqa: E501
        :type: Uuid
        """

        self._construct_uuid = construct_uuid

    @property
    def frame(self):
        """Gets the frame of this PlaymodeData.  # noqa: E501

        Current timeline frame position  # noqa: E501

        :return: The frame of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._frame

    @frame.setter
    def frame(self, frame):
        """Sets the frame of this PlaymodeData.

        Current timeline frame position  # noqa: E501

        :param frame: The frame of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._frame = frame

    @property
    def timecodec(self):
        """Gets the timecodec of this PlaymodeData.  # noqa: E501

        Current timelinetimecode (readonly)  # noqa: E501

        :return: The timecodec of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._timecodec

    @timecodec.setter
    def timecodec(self, timecodec):
        """Sets the timecodec of this PlaymodeData.

        Current timelinetimecode (readonly)  # noqa: E501

        :param timecodec: The timecodec of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._timecodec = timecodec

    @property
    def slot_index(self):
        """Gets the slot_index of this PlaymodeData.  # noqa: E501

        Current Slot index being played in the timeline  # noqa: E501

        :return: The slot_index of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._slot_index

    @slot_index.setter
    def slot_index(self, slot_index):
        """Sets the slot_index of this PlaymodeData.

        Current Slot index being played in the timeline  # noqa: E501

        :param slot_index: The slot_index of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._slot_index = slot_index

    @property
    def shot_uuid(self):
        """Gets the shot_uuid of this PlaymodeData.  # noqa: E501


        :return: The shot_uuid of this PlaymodeData.  # noqa: E501
        :rtype: Uuid
        """
        return self._shot_uuid

    @shot_uuid.setter
    def shot_uuid(self, shot_uuid):
        """Sets the shot_uuid of this PlaymodeData.


        :param shot_uuid: The shot_uuid of this PlaymodeData.  # noqa: E501
        :type: Uuid
        """

        self._shot_uuid = shot_uuid

    @property
    def shot_frame(self):
        """Gets the shot_frame of this PlaymodeData.  # noqa: E501

        Current frame position in the Shot being played  # noqa: E501

        :return: The shot_frame of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._shot_frame

    @shot_frame.setter
    def shot_frame(self, shot_frame):
        """Sets the shot_frame of this PlaymodeData.

        Current frame position in the Shot being played  # noqa: E501

        :param shot_frame: The shot_frame of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._shot_frame = shot_frame

    @property
    def shot_timecode(self):
        """Gets the shot_timecode of this PlaymodeData.  # noqa: E501

        Current record timecode of the Shot being played (readonly)  # noqa: E501

        :return: The shot_timecode of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._shot_timecode

    @shot_timecode.setter
    def shot_timecode(self, shot_timecode):
        """Sets the shot_timecode of this PlaymodeData.

        Current record timecode of the Shot being played (readonly)  # noqa: E501

        :param shot_timecode: The shot_timecode of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._shot_timecode = shot_timecode

    @property
    def version(self):
        """Gets the version of this PlaymodeData.  # noqa: E501

        Version index of the shot in the Player.  # noqa: E501

        :return: The version of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PlaymodeData.

        Version index of the shot in the Player.  # noqa: E501

        :param version: The version of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._version = version

    @property
    def session(self):
        """Gets the session of this PlaymodeData.  # noqa: E501

        Session type the player is in. One of 'timeline,output,derived_output,shot,compare,slot' (readonly).  # noqa: E501

        :return: The session of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._session

    @session.setter
    def session(self, session):
        """Sets the session of this PlaymodeData.

        Session type the player is in. One of 'timeline,output,derived_output,shot,compare,slot' (readonly).  # noqa: E501

        :param session: The session of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._session = session

    @property
    def length(self):
        """Gets the length of this PlaymodeData.  # noqa: E501

        Length of the media in the Player in frames  # noqa: E501

        :return: The length of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this PlaymodeData.

        Length of the media in the Player in frames  # noqa: E501

        :param length: The length of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._length = length

    @property
    def loop(self):
        """Gets the loop of this PlaymodeData.  # noqa: E501

        Loop mode  # noqa: E501

        :return: The loop of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._loop

    @loop.setter
    def loop(self, loop):
        """Sets the loop of this PlaymodeData.

        Loop mode  # noqa: E501

        :param loop: The loop of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._loop = loop

    @property
    def mark_in(self):
        """Gets the mark_in of this PlaymodeData.  # noqa: E501

        View range in-point  # noqa: E501

        :return: The mark_in of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._mark_in

    @mark_in.setter
    def mark_in(self, mark_in):
        """Sets the mark_in of this PlaymodeData.

        View range in-point  # noqa: E501

        :param mark_in: The mark_in of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._mark_in = mark_in

    @property
    def mark_out(self):
        """Gets the mark_out of this PlaymodeData.  # noqa: E501

        View range out-point  # noqa: E501

        :return: The mark_out of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._mark_out

    @mark_out.setter
    def mark_out(self, mark_out):
        """Sets the mark_out of this PlaymodeData.

        View range out-point  # noqa: E501

        :param mark_out: The mark_out of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._mark_out = mark_out

    @property
    def mode(self):
        """Gets the mode of this PlaymodeData.  # noqa: E501

        Playback mode  # noqa: E501

        :return: The mode of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this PlaymodeData.

        Playback mode  # noqa: E501

        :param mode: The mode of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def range(self):
        """Gets the range of this PlaymodeData.  # noqa: E501

        View range is active / not  # noqa: E501

        :return: The range of this PlaymodeData.  # noqa: E501
        :rtype: bool
        """
        return self._range

    @range.setter
    def range(self, range):
        """Sets the range of this PlaymodeData.

        View range is active / not  # noqa: E501

        :param range: The range of this PlaymodeData.  # noqa: E501
        :type: bool
        """

        self._range = range

    @property
    def speed(self):
        """Gets the speed of this PlaymodeData.  # noqa: E501

        Playback multiplier  # noqa: E501

        :return: The speed of this PlaymodeData.  # noqa: E501
        :rtype: int
        """
        return self._speed

    @speed.setter
    def speed(self, speed):
        """Sets the speed of this PlaymodeData.

        Playback multiplier  # noqa: E501

        :param speed: The speed of this PlaymodeData.  # noqa: E501
        :type: int
        """

        self._speed = speed

    @property
    def timeline(self):
        """Gets the timeline of this PlaymodeData.  # noqa: E501

        Name of the construct being played  # noqa: E501

        :return: The timeline of this PlaymodeData.  # noqa: E501
        :rtype: str
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """Sets the timeline of this PlaymodeData.

        Name of the construct being played  # noqa: E501

        :param timeline: The timeline of this PlaymodeData.  # noqa: E501
        :type: str
        """

        self._timeline = timeline

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlaymodeData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlaymodeData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
